//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int idEmpresa { get; set; }
        public string nmEmpresa { get; set; }
        public string nmRazaoSocial { get; set; }
        public string cdCNPJ { get; set; }
    }
}
