//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioAcesso
    {
        public int idUsuario { get; set; }
        public string nmLogin { get; set; }
        public string dsSenha { get; set; }
        public Nullable<bool> flAdmin { get; set; }
        public Nullable<bool> flDesativado { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string dsEmail { get; set; }
        public string nmPrimeiro { get; set; }
        public string nmSegundo { get; set; }
        public Nullable<System.DateTime> dtNascimento { get; set; }
        public string dsGenero { get; set; }
        public string dsPronome { get; set; }
        public string dsGeneroOutro { get; set; }
    }
}
